name: MdEditor

on:
  push:
    branches:
      - 'TaskManager-SPM-add'
      
  pull_request:
    branches: 
      - develop

jobs:
  Test_TaskManagerPackage:
    name: Test TaskManagerPackage
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/rtx-action@v1
      - name: Run Testing
        run: exec ./.github/TaskManagerPackage.sh